---
title: "Project1"
author: "Peter"
date: "1/12/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# load packages

library(zoo)
'library(magrittr)
library(reticulate)'
```

# Indlæser data
```{r}
data <- get(load("armdata.Rdata"))[5][[1]]
pers1 <- data[[1]][[2]]
person <- 10
rep <- 10
x <- c()
y <- c()
z <- c()
for (p in 1:person){
  for (r in 1:rep){
    
    longitude <- data[[p]][[r]][,1]
    x <- cbind(x,data[[p]][[r]][,1])
  }
}
for (p in 1:person){
  for (r in 1:rep){
    
    transversal <- data[[p]][[r]][,2]
    y <- cbind(y,data[[p]][[r]][,2])
  }
}
for (p in 1:person){
  for (r in 1:rep){
    
    vertical <- data[[p]][[r]][,3]
    z <- cbind(z,data[[p]][[r]][,3])
  }
}

x <- t(na.locf(x, fromLast = T))
y <- t(na.locf(y, fromLast = T))
z <- t(na.locf(z, fromLast = T))

colnames <- c( paste0("x_", 1:100),paste0("y_", 1:100),paste0("z_", 1:100))
persons <- c(rep("person1", 10),rep("person2", 10),rep("person3", 10),rep("person4", 10),rep("person5", 10),rep("person6", 10),rep("person7", 10),rep("person8", 10),rep("person9", 10),rep("person10", 10))
reps <- rep(1:10,10)

data_wide <- as.data.frame(cbind(x,y,z), row.names = 1:100)
names(data_wide) <- colnames

data_wide <- cbind(persons,reps,data_wide)
head(data_wide)
```

## Rename data

```{r}
names(data) <- paste0("person_", 1:10)
 
for (per in c(1:length(data))) {
  names(data[[per]]) <- paste0("repetion_", 1:10)
  for (rep in c(1:length(data[[per]]))) {
    colnames(data[[per]][[rep]]) <- c("x", "y", "z")
  }
}
```

## Plots

```{r}
library(rgl)
#cbind(x,y,z)
plot3d(data$person_1$repetion_1, type = 'p', col = heat.colors(1000), lwd = 2, xlab = 'x', ylab = 'y', zlab = 'z')

```


# PCA - test

```{r}

#str(data_wide[,-c(1,2)])
pca <- prcomp(x = data_wide[,-c(1,2)], scale. = T, center = T)
summary(pca)

plot(pca$x, col = data_wide$persons)
```

# Machine learning

Methods

```{r}
names(getModelInfo())
```



#KNN

```{r}
library(class)
set.seed(235)

ind <- sample(100)
knn_data <- data_wide[, -c(1,2)]

train_set <- knn_data[ind[1:80],]
test_set <- knn_data[ind[81:100],]
train_labels <- data_wide$persons[ind[1:80]]
test_labels <- data_wide$persons[ind[81:100]]

#knn_data <- data_wide[, -c(1,2)]
mean(knn(train_set, test_set, train_labels, k = 10) == test_labels)

```


## leave one out

```{r}
library(caret)
data_wide[, -c(1,2)] <- scale(data_wide[, -c(1,2)])

trControl <- trainControl(method  = "LOOCV",
                          number  = 5)

fit <- train(persons ~ .,
             method     = "knn",
             tuneGrid   = expand.grid(k = 1:10),
             trControl  = trControl,
             metric     = "Accuracy",
             data       = data_wide[,-2])

fit
```






